In [12]:
import pandas as pd
df=pd.read_csv('NFLX.csv')
df.head()

Date        Open        High         Low       Close   Adj Close  \
0  2015-12-16  119.800003  123.000000  118.089996  122.639999  122.639999   
1  2015-12-17  123.970001  126.349998  122.419998  122.510002  122.510002   
2  2015-12-18  120.849998  122.190002  117.919998  118.019997  118.019997   
3  2015-12-21  119.510002  119.589996  115.660004  116.629997  116.629997   
4  2015-12-22  117.300003  117.430000  114.860001  116.239998  116.239998   

     Volume  
0  13181000  
1  17284900  
2  17948100  
3  11670000  
4   9689000

In [16]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [20]:
df['High'].mean()

229.97297904468715

In [22]:
df['Low'].std()

101.45861102484213

In [24]:
df.iloc[0:5,2:4]

High         Low
0  123.000000  118.089996
1  126.349998  122.419998
2  122.190002  117.919998
3  119.589996  115.660004
4  117.430000  114.860001

In [28]:
df.loc[[2],['High']]

High
2  122.190002

In [34]:
df3=df.iloc[:,0:3]
df3.head()

Date        Open        High
0  2015-12-16  119.800003  123.000000
1  2015-12-17  123.970001  126.349998
2  2015-12-18  120.849998  122.190002
3  2015-12-21  119.510002  119.589996
4  2015-12-22  117.300003  117.430000

In [36]:
df.dtypes

Date          object
Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume         int64
dtype: object

In [38]:
df_test = df.rename(columns={'Low':'Test'})
df_test.head()

Date        Open        High        Test       Close   Adj Close  \
0  2015-12-16  119.800003  123.000000  118.089996  122.639999  122.639999   
1  2015-12-17  123.970001  126.349998  122.419998  122.510002  122.510002   
2  2015-12-18  120.849998  122.190002  117.919998  118.019997  118.019997   
3  2015-12-21  119.510002  119.589996  115.660004  116.629997  116.629997   
4  2015-12-22  117.300003  117.430000  114.860001  116.239998  116.239998   

     Volume  
0  13181000  
1  17284900  
2  17948100  
3  11670000  
4   9689000

In [40]:
import numpy as np
array1= np.array([1,2,3,4,5,6,7,8,9])

In [42]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
type(array1)

numpy.ndarray

**What is the difference berween List and Array?**

In Python, both lists and arrays are used to store collections of elements, but they have some differences in terms of functionality and implementation. Here's a breakdown of the key differences between lists and arrays in Python:

**Data Type:**
Lists: Lists in Python are a built-in data type and are part of the standard library. They can hold elements of different data types and are very flexible.
Arrays: Arrays in Python are not a built-in data type but are provided by external libraries like NumPy. Arrays are more rigid in terms of data types and often store homogeneous elements (elements of the same data type) for optimized computation.

**Functionality:**
Lists: Lists provide various methods and operations for adding, removing, and manipulating elements.
Arrays: Arrays, particularly those from libraries like NumPy, provide extensive mathematical operations and optimizations for numerical computations.

**Memory Efficiency:**
Lists: Lists in Python are less memory efficient compared to arrays because they store additional metadata for each element, such as the type of the element and its reference count.

**In summary, the choice between using lists or arrays depends on your specific needs. If you're dealing with general data storage and manipulation, lists are more suitable. If you're working with numerical data and require optimized computations, arrays from libraries like NumPy offer better performance and functionality.**

In [52]:
#create 2D array
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
array3=np.array(
    [[[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,16],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]]
)
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 16],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [58]:
array1.shape

(9,)

In [60]:
array2.shape

(3, 3)

In [62]:
array3.shape

(3, 3, 3)

In [64]:
array3.ndim

3

In [66]:
#u=sing linspace

np.linspace(200,900,num=3)

array([200., 550., 900.])

In [18]:
import pandas as pd
df_usedcar_data1=pd.read_csv('test.csv')
df_usedcar_data1.head()

ID Levy Manufacturer   Model  Prod. year   Category Leather interior  \
0  44020629    -   VOLKSWAGEN    Golf        2012  Hatchback               No   
1  45784798    -      HYUNDAI  Sonata        2012      Sedan              Yes   
2  45800257    -       NISSAN   Tiida        2005      Sedan               No   
3  45797981  975        VOLVO    XC90        2012       Jeep              Yes   
4  45814303    -         OPEL   Astra        1993  Hatchback               No   

  Fuel type Engine volume    Mileage  Cylinders Gear box type Drive wheels  \
0    Diesel     2.0 Turbo       0 km          4        Manual        Front   
1    Petrol           2.4   26000 km          4     Tiptronic        Front   
2    Petrol           1.5  168000 km          4     Automatic        Front   
3    Petrol           3.2  143000 km          6     Automatic          4x4   
4    Petrol           1.6  200000 km          4        Manual        Front   

    Doors             Wheel     Color  Airbags  Price  
0  02-Mar        Left wheel      Grey       10    NaN  
1  04-May        Left wheel      Grey       10    NaN  
2  04-May  Right-hand drive  Sky blue        8    NaN  
3  04-May        Left wheel      Blue       12    NaN  
4  04-May        Left wheel     Black        0    NaN

In [20]:
df_usedcar_data2=pd.read_csv('train.csv')
df_usedcar_data2.head()

ID  Price  Levy Manufacturer    Model  Prod. year   Category  \
0  45654403  13328  1399        LEXUS   RX 450        2010       Jeep   
1  44731507  16621  1018    CHEVROLET  Equinox        2011       Jeep   
2  45774419   8467     -        HONDA      FIT        2006  Hatchback   
3  45769185   3607   862         FORD   Escape        2011       Jeep   
4  45809263  11726   446        HONDA      FIT        2014  Hatchback   

  Leather interior Fuel type Engine volume    Mileage  Cylinders  \
0              Yes    Hybrid           3.5  186005 km        6.0   
1               No    Petrol             3  192000 km        6.0   
2               No    Petrol           1.3  200000 km        4.0   
3              Yes    Hybrid           2.5  168966 km        4.0   
4              Yes    Petrol           1.3   91901 km        4.0   

  Gear box type Drive wheels   Doors             Wheel   Color  Airbags  
0     Automatic          4x4  04-May        Left wheel  Silver       12  
1     Tiptronic          4x4  04-May        Left wheel   Black        8  
2      Variator        Front  04-May  Right-hand drive   Black        2  
3     Automatic          4x4  04-May        Left wheel   White        0  
4     Automatic        Front  04-May        Left wheel  Silver        4

In [22]:
used_carData_All=[df_usedcar_data1,df_usedcar_data2]
df_used_carData_All=pd.concat(used_carData_All)
df_used_carData_All=df_used_carData_All.reset_index(drop=True)
df_used_carData_All.head()

ID Levy Manufacturer   Model  Prod. year   Category Leather interior  \
0  44020629    -   VOLKSWAGEN    Golf        2012  Hatchback               No   
1  45784798    -      HYUNDAI  Sonata        2012      Sedan              Yes   
2  45800257    -       NISSAN   Tiida        2005      Sedan               No   
3  45797981  975        VOLVO    XC90        2012       Jeep              Yes   
4  45814303    -         OPEL   Astra        1993  Hatchback               No   

  Fuel type Engine volume    Mileage  Cylinders Gear box type Drive wheels  \
0    Diesel     2.0 Turbo       0 km        4.0        Manual        Front   
1    Petrol           2.4   26000 km        4.0     Tiptronic        Front   
2    Petrol           1.5  168000 km        4.0     Automatic        Front   
3    Petrol           3.2  143000 km        6.0     Automatic          4x4   
4    Petrol           1.6  200000 km        4.0        Manual        Front   

    Doors             Wheel     Color  Airbags  Price  
0  02-Mar        Left wheel      Grey       10    NaN  
1  04-May        Left wheel      Grey       10    NaN  
2  04-May  Right-hand drive  Sky blue        8    NaN  
3  04-May        Left wheel      Blue       12    NaN  
4  04-May        Left wheel     Black        0    NaN

In [86]:
df_used_carData_All.shape

(27482, 18)

In [48]:
df_used_carData_All.iloc[0,3]

'Golf'

In [104]:
df_used_carData_All.ID.unique

<bound method Series.unique of 0        44020629
1        45784798
2        45800257
3        45797981
4        45814303
           ...   
27477    45798355
27478    45778856
27479    45804997
27480    45793526
27481    45813273
Name: ID, Length: 27482, dtype: int64>

In [106]:
df_used_carData_All.ID

0        44020629
1        45784798
2        45800257
3        45797981
4        45814303
           ...   
27477    45798355
27478    45778856
27479    45804997
27480    45793526
27481    45813273
Name: ID, Length: 27482, dtype: int64